apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-operator

resources:
- pgadmin.yaml

secretGenerator:
- name: pgadmin-password-secret
  literals:
  - dba-password=pgadmin
  type: Opaque

generatorOptions:
  disableNameSuffixHash: true
